# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  COVERFILE: cover.out
  TARGET_DIR: build
  TARGET_BIN: rat


tasks:
  default:
    desc: Same as build, can be invoked by running `task` without arguments
    cmds:
      - task: build

  build:
    desc: "Build the program and output to {{.TARGET_DIR}}/{{.TARGET_BIN}}"
    cmds:
      - go build -o {{.TARGET_DIR}}/{{.TARGET_BIN}} main.go
    sources:
      - "**/*.go"
      - go.mod
      - exclude: "**/*_test.go"
    generates:
      - "{{.TARGET_DIR}}/{{.TARGET_BIN}}"

  ci:
    desc: Run CI tasks
    deps:
      - ci:lint
      - ci:tidy
      - ci:test
    cmds:
      - task: ci:build

  ci:build:
    cmd: go build -o {{.TARGET_DIR}}/{{.TARGET_BIN}} main.go

  ci:lint:
    - task: lint
    
  ci:test: go test ./... -coverprofile {{.TARGET_DIR}}/{{.COVERFILE}}
    
  ci:tidy: go mod tidy -diff

  lint:
    desc: Lint source code files
    cmds:
      - golangci-lint run
      - markdownlint-cli2 "**/*.md"
    sources:
      - "**/*.go"
      - "**/*.md"
      - ".golangci.toml"
    ignore_error: true

  run:
    desc: Run the program. Use `task run -- args` to pass in arguments.
    cmd: go run main.go {{.CLI_ARGS}}

  test:
    desc: Run Go unit tests
    cmd: go test ./...
    sources:
      - "**/*.go"
      - go.mod
      - exclude: cmd/**/*.go
